### PR TITLE
Fix Thread.current with a Fiber pool

### LINKED ISSUE #903: Thread#current and Fiber#transfer gets the wrong Ruby Thread due to Fiber pooling
Originally discovered by @chuckremes with the script:
https://gist.github.com/chuckremes/14c9ef06efc0bc62b9dc5b588c06719f

A similar bug seems to also happen on Rubinius:
https://github.com/rubinius/rubinius/issues/3776

### PR DESCRIPTION
**Pull request by eregon**
Fixes #903

### CODE REVIEW

File: src/main/java/org/truffleruby/core/thread/GetCurrentRubyThreadNode.java [hunk 1]
```diff
@@ -24,13 +25,24 @@ public static GetCurrentRubyThreadNode create() {
...
-    @Specialization(
-            guards = "getCurrentJavaThread(frame) == cachedJavaThread",
-            limit = "getCacheLimit()"
-    )
+    /*
+     * Note: the frame argument is used as a dynamic parameter here. Otherwise, The TruffleDSL
+     * assumes cached parameters or calls with only cached arguments (including calls with no
+     * arguments) never change.
+     */
+    /*
```
Comment (chrisseaton) [inline src/main/java/org/truffleruby/core/thread/GetCurrentRubyThreadNode.java]: It's weird to have two comment blocks like this back to back. But I won't make you change it.

Comment (eregon) [reply src/main/java/org/truffleruby/core/thread/GetCurrentRubyThreadNode.java]: My IDE merged them initially, so I did that.
Adding an empty line in between seems to workaround that problem, so it's fixed now.
